[package]
name = "gba_save"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true

[dependencies]
deranged = {version = "0.3.9", default-features = false}
embedded-io = "0.6.1"

[dev-dependencies]
claims = "0.7.1"
gba_test = {version = "0.1.3", features = ["log"]}
mgba_log = "0.2.1"
more_ranges = "0.1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(sram)", "cfg(flash_64k)", "cfg(flash_128k)"]}
