name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - run: sudo apt-get install binutils-arm-none-eabi
    - run: cargo test --no-run --message-format=json | tee results.json
    - run: cargo install parse_test_executable
    - run: echo "ROM_PATH=$(parse_test_executable results.json)" >> $GITHUB_ENV
    - run: arm-none-eabi-objcopy -O binary ${{ env.ROM_PATH }} test.gba
    - run: cargo install gbafix
    - run: gbafix test.gba
    - uses: Anders429/github-mgba-rom-test@config
      with:
        swi-call: 0x27
        read-register: 'r0'
        rom-path: test.gba
        success-code: 0  # Pass
